---
- name: Install dependencies for Nagios on CentOS
  yum:
    name:
      - httpd
      - php
      - wget
    state: present

- name: Download Nagios tarball
  get_url:
    url: https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.6.tar.gz
    dest: /tmp/nagios.tar.gz

- name: Extract Nagios tarball
  unarchive:
    src: /tmp/nagios.tar.gz
    dest: /opt/
    remote_src: yes

- name: Compile and Install Nagios
  command: ./configure --with-httpd-conf=/etc/httpd/conf.d/ && make all && make install && make install-init && make install-config && make install-commandmode && make install-webconf
  args:
    chdir: /opt/nagios-4.4.6

- name: Configure Nagios Admin User
  command: htpasswd -b -c /usr/local/nagios/etc/htpasswd.users nagiosadmin password

- name: Enable and Start Apache
  systemd:
    name: httpd
    enabled: yes
    state: started
